# Generated by Django 3.0.6 on 2020-05-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howru_models', '0002_remove_patient_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='_picture',
            field=models.BinaryField(blank=True, db_column='picture'),
        ),
    ]
